version: '3.8'
services:
  app:
    container_name: btc-api
    build: .
    volumes:
      - ./db/users:/usr/src/app/db/users
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
    ports:
      - '5007:5007'
    depends_on:
      - rabbitmq
      - btc-service
  btc-service:
    container_name: btc-service
    build: ./btcMicroService/
    ports:
      - '5008:5008'
    volumes:
      - ./btcMicroService/src:/usr/src/app/src
      - ./btcMicroService/.env:/usr/src/app/.env
  logs-consumer:
    container_name: logs-consumer
    build: ./logsConsumer/
    volumes:
      - ./logsConsumer/src:/usr/src/app/src
      - ./logsConsumer/.env:/usr/src/app/.env
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
